[[keyboard.bindings]]
key = "Key1"
mods = "Alt"
chars = "\u001b1"

[[keyboard.bindings]]
key = "Key2"
mods = "Alt"
chars = "\u001b2"

[[keyboard.bindings]]
key = "Key3"
mods = "Alt"
chars = "\u001b3"

[[keyboard.bindings]]
key = "Key4"
mods = "Alt"
chars = "\u001b4"

[[keyboard.bindings]]
key = "Key5"
mods = "Alt"
chars = "\u001b5"

[[keyboard.bindings]]
key = "Key6"
mods = "Alt"
chars = "\u001b6"

[[keyboard.bindings]]
key = "Key7"
mods = "Alt"
chars = "\u001b7"

[[keyboard.bindings]]
key = "Key8"
mods = "Alt"
chars = "\u001b8"

[[keyboard.bindings]]
key = "Key9"
mods = "Alt"
chars = "\u001b9"
